// SDR 3.5 — client entry point (LoomVTT native ruleset)
// Generated by _tools/scaffold-ruleset.mjs — mechanics and sheets land in handoffs 02/03.
import { SystemRegistry, defineSystem, statusEffects, sheets } from '/_loom/sdk/index.js';
import { registerSettings } from './scripts/settings.mjs';
import { getDefaultData } from './scripts/schema.mjs';
import { prepareActorRow } from './scripts/prepare-data.mjs';
import { getSheetSchema, getItemSheetSchema } from './scripts/sheet-schemas.mjs';
import { SYSTEM_ID, CONDITIONS } from './scripts/config.mjs';
import { Srd35Api } from './scripts/api.mjs';
import { Srd35CharacterSheet } from './scripts/character-sheet.mjs';
import { Srd35NpcSheet } from './scripts/npc-sheet.mjs';
import { Srd35ItemSheet } from './scripts/item-sheet.mjs';

function prepareData(row) {
  return prepareActorRow(row);
}

registerSettings();

SystemRegistry.register(defineSystem({
  id: SYSTEM_ID,
  title: 'SDR 3.5',
  version: '0.1.0',
  actorTypes: ['character', 'npc'],
  itemTypes: ['race', 'class', 'feat', 'class-feature', 'spell', 'weapon', 'armor', 'shield', 'equipment', 'consumable'],
  getDefaultData,
  getSheetSchema,
  getItemSheetSchema,
  prepareData,
}));

for (const cond of CONDITIONS) {
  if (!statusEffects.get?.(cond.id)) statusEffects.register(cond);
}

sheets.catalog('actor', 'character', Srd35CharacterSheet);
sheets.catalog('actor', 'npc', Srd35NpcSheet);
sheets.catalog('item', '*', Srd35ItemSheet);

window.SRD35 = Srd35Api;
